"""
inject_manual_run.py

Injects a manually-run benchmark result (from Claude subagents) into the
benchmark_runs directory in the same format as the real benchmark pipeline.

Usage:
    python scripts/inject_manual_run.py

Add a new entry to MANUAL_RUNS below for each completed task/architecture.
Then run this script to write the JSON files.
"""

from __future__ import annotations

import json
import sys
from dataclasses import asdict
from datetime import UTC, datetime
from pathlib import Path

# Make the src package importable
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from agentic_research.benchmark import (
    BenchmarkRunRecord,
    _aggregate,
    _TASK_FOLDER_LABEL,
)
from agentic_research.sample_tasks import get_task

# ---------------------------------------------------------------------------
# ADD YOUR MANUAL RUNS HERE
# Each dict maps to a BenchmarkRunRecord. Fields you don't have set to None/[].
# ---------------------------------------------------------------------------
MANUAL_RUNS = [

    # -------------------------------------------------------------------------
    # Task 1: requests-netrc-empty-default — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:00Z",
        "task_id": "requests-netrc-empty-default",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 38.979,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 9,
        "tokens_used": 13422,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 13422},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["src/requests/utils.py"],
        "issue_summary": "get_netrc_auth() returns ('', '') instead of None for .netrc files with a bare default stanza.",
        "root_cause": "('', '', '') is truthy as a tuple so `if _netrc:` passes; login_i becomes 1 due to empty string, returning ('', '') instead of None.",
        "validation_report": "2/2 tests passed: test_empty_default_credentials_ignored PASSED, test_valid_credentials_still_returned PASSED.",
        "review_notes": "",
        "patch_summary": "Changed `if _netrc:` to `if _netrc and any(_netrc):` on line 234 of src/requests/utils.py.",
        "current_patch": "if _netrc and any(_netrc):",
        "test_stdout": "2 passed in 0.01s",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 1: requests-netrc-empty-default — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:01Z",
        "task_id": "requests-netrc-empty-default",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "revise",
        "latency_seconds": 74.597,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 8,
        "tokens_used": 56313,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 11647,
            "analyst": 11870,
            "engineer": 10630,
            "tester": 10680,
            "reviewer": 11486,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["src/requests/utils.py"],
        "issue_summary": "get_netrc_auth() returns ('', '') instead of None for .netrc files with a bare default stanza.",
        "root_cause": "('', '', '') is truthy as a tuple so `if _netrc:` passes; login_i becomes 1 due to empty string, returning ('', '') instead of None. Analyst noted any(_netrc) includes irrelevant account field; (_netrc[0] or _netrc[2]) would be more precise.",
        "validation_report": "2/2 tests passed: test_empty_default_credentials_ignored PASSED, test_valid_credentials_still_returned PASSED.",
        "review_notes": "REVISE: any(_netrc) evaluates the account field (index 1) which is irrelevant to auth. More precise guard: (_netrc[0] or _netrc[2]). Existing line 236 fallback logic already handles empty login, so any(_netrc) conflicts with it.",
        "patch_summary": "Changed `if _netrc:` to `if _netrc and any(_netrc):` on line 234 of src/requests/utils.py.",
        "current_patch": "if _netrc and any(_netrc):",
        "test_stdout": "2 passed in 0.01s",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try. Reviewer flagged: any(_netrc) includes irrelevant account field; (_netrc[0] or _netrc[2]) would be more precise.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 2: click-flag-value-optional — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:01:00Z",
        "task_id": "click-flag-value-optional",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 108.956,
        "iterations": 2,
        "revision_count": 1,
        "llm_calls_used": 28,
        "tokens_used": 23931,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 23931},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["src/click/core.py"],
        "issue_summary": "Option with is_flag=False and flag_value raises 'requires an argument' instead of using flag_value as the value.",
        "root_cause": "_flag_needs_value not set to True when flag_value is set and default is also provided. Parser demands argument instead of emitting FLAG_NEEDS_VALUE sentinel.",
        "validation_report": "3/3 tests passed.",
        "review_notes": "",
        "patch_summary": "Changed line 2783: self._flag_needs_value = self.default is UNSET → self.default is UNSET or flag_value is not UNSET",
        "current_patch": "self._flag_needs_value = self.default is UNSET or flag_value is not UNSET",
        "test_stdout": "3 passed in 0.01s",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "2 attempts. FAILED first attempt: wrote `flag_value is UNSET` (inverted condition — logically backwards, would have blocked valid flag_value cases). Self-corrected on second attempt.",
        "first_attempt_passed": False,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 2: click-flag-value-optional — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:02:00Z",
        "task_id": "click-flag-value-optional",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "revise",
        "latency_seconds": 82.057,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 13,
        "tokens_used": 63632,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 15921,
            "analyst": 14681,
            "engineer": 10716,
            "tester": 10572,
            "reviewer": 11742,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["src/click/core.py"],
        "issue_summary": "Option with is_flag=False and flag_value raises 'requires an argument' instead of using flag_value as the value.",
        "root_cause": "_flag_needs_value not set to True when flag_value is set and default is also provided. Parser demands argument instead of emitting FLAG_NEEDS_VALUE sentinel.",
        "validation_report": "3/3 tests passed.",
        "review_notes": "REVISE: fix regresses the case where both flag_value AND default are set with is_flag=False — flag_value is not UNSET forces _flag_needs_value=True overriding the default.",
        "patch_summary": "Changed line 2783: self._flag_needs_value = self.default is UNSET → flag_value is not UNSET or self.default is UNSET",
        "current_patch": "self._flag_needs_value = flag_value is not UNSET or self.default is UNSET",
        "test_stdout": "3 passed in 0.01s",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try. Reviewer flagged edge case: fix regresses case where both flag_value AND default are set with is_flag=False.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 3: werkzeug-safe-join-device-names — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:03:00Z",
        "task_id": "werkzeug-safe-join-device-names",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 57.483,
        "iterations": 2,
        "revision_count": 1,
        "llm_calls_used": 15,
        "tokens_used": 18054,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 18054},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["src/werkzeug/security.py"],
        "issue_summary": "safe_join() only checks final path segment for Windows device names. 'b/CON' bypasses the check.",
        "root_cause": "filename.partition('.')[0] on 'b/CON' gives 'b/CON' which is not in _windows_device_files. Also os.name=='nt' guard skips check entirely on macOS/Linux.",
        "validation_report": "4/4 tests passed.",
        "review_notes": "",
        "patch_summary": "Replaced single-segment device name check with loop over filename.split('/'), removed os.name=='nt' guard.",
        "current_patch": "any(seg.partition('.')[0].strip().upper() in _windows_device_files for seg in filename.split('/') if seg)",
        "test_stdout": "4 passed in 0.03s",
        "test_stderr": "",
        "attempt_notes": "2 attempts. FAILED first attempt: kept os.name=='nt' guard which skips check entirely on macOS. Removed guard on second attempt.",
        "first_attempt_passed": False,
        "selected_branch_id": "",
        "branch_results": [],
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 3: werkzeug-safe-join-device-names — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:04:00Z",
        "task_id": "werkzeug-safe-join-device-names",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 90.152,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 7,
        "tokens_used": 52311,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 12987,
            "analyst": 12633,
            "engineer": 12865,
            "tester": 6913,
            "reviewer": 6913,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["src/werkzeug/security.py"],
        "issue_summary": "safe_join() only checks final path segment for Windows device names. 'b/CON' bypasses the check.",
        "root_cause": "filename.partition('.')[0] on 'b/CON' gives 'b/CON' which is not in _windows_device_files. os.name=='nt' guard also skips check on non-Windows. Analyst correctly identified both issues.",
        "validation_report": "4/4 tests passed.",
        "review_notes": "ACCEPT. Reviewer noted: _os_alt_seps still platform-conditional (backslash edge case), and suggested adding tests for device names with extensions (NUL.txt, PRN ) to lock in strip logic.",
        "patch_summary": "Replaced single-segment device name check with loop over filename.split('/'), removed os.name=='nt' guard.",
        "current_patch": "any(seg.partition('.')[0].strip().upper() in _windows_device_files for seg in filename.split('/') if seg)",
        "test_stdout": "4 passed in 0.01s",
        "test_stderr": "",
        "attempt_notes": "1 attempt. Analyst explicitly identified os.name=='nt' guard issue before engineer touched code — got it right first try.",
        "first_attempt_passed": True,
        "selected_branch_id": "",
        "branch_results": [],
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 4: flask-provide-automatic-options — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:05:00Z",
        "task_id": "flask-provide-automatic-options",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 30.474,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 7,
        "tokens_used": 13939,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 13939},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["src/flask/sansio/app.py"],
        "issue_summary": "provide_automatic_options=True passed explicitly does not enable OPTIONS — the required_methods.add('OPTIONS') is inside a block that gets skipped.",
        "root_cause": "required_methods.add('OPTIONS') lived inside the second `if provide_automatic_options is None` block — skipped when value came from view_func or explicit caller arg.",
        "validation_report": "3/3 tests passed.",
        "review_notes": "",
        "patch_summary": "Separated value resolution from required_methods.add — OPTIONS now added unconditionally when provide_automatic_options is True.",
        "current_patch": "if provide_automatic_options and 'OPTIONS' not in methods: required_methods.add('OPTIONS')",
        "test_stdout": "3 passed in 0.02s",
        "test_stderr": "",
        "attempt_notes": "1 attempt. Correct on first try.",
        "first_attempt_passed": True,
        "selected_branch_id": "",
        "branch_results": [],
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 4: flask-provide-automatic-options — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:06:00Z",
        "task_id": "flask-provide-automatic-options",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 42.501,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 5,
        "tokens_used": 24423,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 12454,
            "analyst": 3990,
            "engineer": 3990,
            "tester": 1990,
            "reviewer": 1999,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["src/flask/sansio/app.py"],
        "issue_summary": "provide_automatic_options=True passed explicitly does not enable OPTIONS — the required_methods.add('OPTIONS') is inside a block that gets skipped.",
        "root_cause": "required_methods.add('OPTIONS') lived inside the second `if provide_automatic_options is None` block — skipped when value came from view_func or explicit caller arg.",
        "validation_report": "3/3 tests passed.",
        "review_notes": "ACCEPT. Decoupling value resolution from required_methods.add is correct semantics. No regression risk — False/existing OPTIONS cases handled correctly.",
        "patch_summary": "Separated value resolution from required_methods.add — OPTIONS now added unconditionally when provide_automatic_options is True.",
        "current_patch": "if provide_automatic_options and 'OPTIONS' not in methods: required_methods.add('OPTIONS')",
        "test_stdout": "3 passed in 0.02s",
        "test_stderr": "",
        "attempt_notes": "1 attempt. Correct on first try.",
        "first_attempt_passed": True,
        "selected_branch_id": "",
        "branch_results": [],
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 5: flask-teardown-all-callbacks — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:07:00Z",
        "task_id": "flask-teardown-all-callbacks",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 188.501,
        "iterations": 3,
        "revision_count": 2,
        "llm_calls_used": 41,
        "tokens_used": 39779,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 39779},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["src/flask/app.py", "src/flask/ctx.py", "src/flask/helpers.py"],
        "issue_summary": "do_teardown_request and do_teardown_appcontext stop on first callback exception, skipping remaining callbacks.",
        "root_cause": "Sequential callback iteration with no exception handling — first raise exits the loop. Also ctx.pop() didn't protect _cv_app.reset() in a finally block.",
        "validation_report": "2/2 tests passed.",
        "review_notes": "",
        "patch_summary": "Added _CollectErrors helper, wrapped callbacks in try/except in app.py, protected _cv_app.reset() with finally in ctx.py.",
        "current_patch": "_CollectErrors context manager collects exceptions; reraise() re-raises first after all callbacks run.",
        "test_stdout": "2 passed in 0.03s",
        "test_stderr": "",
        "attempt_notes": "3 attempts. FAILED attempt 1: fix worked but do_teardown_request called twice (manually in test + by with-block exit). FAILED attempt 2: _cv_app.reset() not called when appcontext teardown raised, leaving dangling context. Fixed both on attempt 3.",
        "first_attempt_passed": False,
        "selected_branch_id": "",
        "branch_results": [],
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 5: flask-teardown-all-callbacks — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:08:00Z",
        "task_id": "flask-teardown-all-callbacks",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 109.905,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 15,
        "tokens_used": 45534,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 9107,
            "analyst": 9107,
            "engineer": 13613,
            "tester": 6854,
            "reviewer": 6853,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["src/flask/app.py", "src/flask/ctx.py"],
        "issue_summary": "do_teardown_request and do_teardown_appcontext stop on first callback exception, skipping remaining callbacks.",
        "root_cause": "Sequential callback iteration with no exception handling. Also ctx.pop() didn't protect _cv_app.reset() in finally — dangling context on teardown error.",
        "validation_report": "2/2 tests passed.",
        "review_notes": "ACCEPT. Minimal, correct, handles context-var cleanup edge case. Exception collection uses Exception not BaseException — matches Flask patterns.",
        "patch_summary": "Wrapped callbacks in try/except in app.py collecting errors, re-raise first after all run. Protected _cv_app.reset() with finally in ctx.py.",
        "current_patch": "try/except per callback, errors list, re-raise first error after loop.",
        "test_stdout": "2 passed in 0.01s",
        "test_stderr": "",
        "attempt_notes": "1 attempt. Analyst identified both issues (callback loop AND ctx var cleanup) before engineer touched code — got it right first try.",
        "first_attempt_passed": True,
        "selected_branch_id": "",
        "branch_results": [],
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 6: gin-data-render-content-length — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:10Z",
        "task_id": "gin-data-render-content-length",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 19.475,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 4,
        "tokens_used": 11494,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 11494},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["render/data.go"],
        "issue_summary": "Data.Render() writes binary body without explicitly setting Content-Length header.",
        "root_cause": "render/data.go called w.Write(r.Data) without first calling w.Header().Set(\"Content-Length\", ...), so clients relying on the header could hang or misread the response length.",
        "validation_report": "3/3 subtests passed: TestRealDataContentLength/1, /100, /1000 all PASS.",
        "review_notes": "",
        "patch_summary": "Added strconv import and if len(r.Data) > 0 { w.Header().Set(\"Content-Length\", strconv.Itoa(len(r.Data))) } before w.Write in render/data.go.",
        "current_patch": "if len(r.Data) > 0 { w.Header().Set(\"Content-Length\", strconv.Itoa(len(r.Data))) }",
        "test_stdout": "3 subtests passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 6: gin-data-render-content-length — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:11Z",
        "task_id": "gin-data-render-content-length",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "revise",
        "latency_seconds": 94.874,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 20,
        "tokens_used": 60450,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 10632,
            "analyst": 13681,
            "engineer": 11008,
            "tester": 10477,
            "reviewer": 14652,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["render/data.go"],
        "issue_summary": "Data.Render() writes binary body without explicitly setting Content-Length header.",
        "root_cause": "render/data.go called w.Write(r.Data) without first calling w.Header().Set(\"Content-Length\", ...). Analyst confirmed WriteContentType does not flush headers, so ordering is safe.",
        "validation_report": "3/3 subtests passed: TestRealDataContentLength/1, /100, /1000 all PASS.",
        "review_notes": "REVISE: Reviewer flagged gzip middleware regression risk (compressed body length differs from len(r.Data)), ordering fragility if WriteContentType ever flushes, and missing zero-length test case.",
        "patch_summary": "Added strconv import and if len(r.Data) > 0 { w.Header().Set(\"Content-Length\", strconv.Itoa(len(r.Data))) } before w.Write in render/data.go.",
        "current_patch": "if len(r.Data) > 0 { w.Header().Set(\"Content-Length\", strconv.Itoa(len(r.Data))) }",
        "test_stdout": "3 subtests passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try. Reviewer flagged gzip middleware risk and ordering fragility.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 7: gin-form-binding-empty-slice — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:12Z",
        "task_id": "gin-form-binding-empty-slice",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 88.821,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 10,
        "tokens_used": 14535,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 14535},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["binding/form_mapping.go"],
        "issue_summary": "Form binding does not fall back to default for slice/array fields when the key is present but has zero values.",
        "root_cause": "setByForm used `!ok` (key absent) instead of `len(vs) == 0` (key present but empty), causing the default-value branch to be skipped and panicking on vs[0].",
        "validation_report": "3/3 subtests passed: empty_slice_with_default_falls_back_to_default, empty_slice_without_default_returns_nil, slice_with_values_ignores_default.",
        "review_notes": "",
        "patch_summary": "Changed !ok to len(vs)==0 on lines 228, 234, 254 of binding/form_mapping.go; removed unused ok variable.",
        "current_patch": "if len(vs) == 0 && !opt.isDefaultExists { ... } / if len(vs) == 0 { vs = []string{opt.defaultValue} }",
        "test_stdout": "3 subtests passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 7: gin-form-binding-empty-slice — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:13Z",
        "task_id": "gin-form-binding-empty-slice",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "revise",
        "latency_seconds": 76.522,
        "iterations": 2,
        "revision_count": 1,
        "llm_calls_used": 9,
        "tokens_used": 61600,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 15507,
            "analyst": 11823,
            "engineer": 11544,
            "tester": 10437,
            "reviewer": 12289,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["binding/form_mapping.go"],
        "issue_summary": "Form binding does not fall back to default for slice/array fields when the key is present but has zero values.",
        "root_cause": "setByForm used `!ok` instead of `len(vs)==0`. Analyst correctly identified that removing `ok` would break lines 244, 264, 279 — but engineer removed it anyway, causing a compile error. Coordinator fixed by restoring `ok` in the map lookup.",
        "validation_report": "3/3 subtests passed after correction.",
        "review_notes": "REVISE: Reviewer flagged dead code in default branch (line 279 `if !ok` is now unreachable), medium regression risk for callers using explicit empty slices, and missing test coverage for scalar kind with empty slice.",
        "patch_summary": "Changed !ok to len(vs)==0 on lines 228, 234, 254; kept ok variable for use on lines 244, 264, 279.",
        "current_patch": "if len(vs) == 0 && !opt.isDefaultExists { ... } / if len(vs) == 0 { vs = []string{opt.defaultValue} }",
        "test_stdout": "3 subtests passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "FAILED attempt 1 (engineer): removed ok variable but it was still used on lines 244/264/279, causing compile error. Correct on attempt 2 after restoring ok in map lookup.",
        "first_attempt_passed": False,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 8: gin-literal-colon-route — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:14Z",
        "task_id": "gin-literal-colon-route",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 21.350,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 4,
        "tokens_used": 20521,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 20521},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["gin.go"],
        "issue_summary": "Routes with literal colons fail when ServeHTTP is called without Run().",
        "root_cause": "updateRouteTrees() only called in Run(). Direct ServeHTTP usage skipped it so routes like /test\\:action never matched.",
        "validation_report": "2/2 tests passed: TestRealLiteralColonDirectServeHTTP PASS, TestRealLiteralColonViaHandler PASS.",
        "review_notes": "",
        "patch_summary": "Added onceUpdateRouteTrees sync.Once to Engine struct; engine.onceUpdateRouteTrees.Do() in ServeHTTP and Run().",
        "current_patch": "engine.onceUpdateRouteTrees.Do(engine.updateRouteTrees)",
        "test_stdout": "2 tests passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 8: gin-literal-colon-route — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:15Z",
        "task_id": "gin-literal-colon-route",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "revise",
        "latency_seconds": 101.818,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 19,
        "tokens_used": 73747,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 19299,
            "analyst": 14435,
            "engineer": 10981,
            "tester": 9594,
            "reviewer": 19438,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["gin.go"],
        "issue_summary": "Routes with literal colons fail when ServeHTTP is called without Run().",
        "root_cause": "updateRouteTrees() only called in Run(). Analyst confirmed sync.Once correct; noted RunTLS/RunUnix also bypass Run() but ServeHTTP guard covers them.",
        "validation_report": "2/2 tests passed.",
        "review_notes": "REVISE: sync.Once permanently consumed — engine reuse after route changes won't re-run updateRouteTrees. RunTLS/RunUnix/etc don't call Do proactively. sync.Once wrong primitive; atomic generation counter preferred.",
        "patch_summary": "Added onceUpdateRouteTrees sync.Once to Engine; Do() in ServeHTTP and Run().",
        "current_patch": "engine.onceUpdateRouteTrees.Do(engine.updateRouteTrees)",
        "test_stdout": "2 tests passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try. Reviewer flagged sync.Once reuse limitation.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 9: validator-panic-unique-nil-pointer — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:16Z",
        "task_id": "validator-panic-unique-nil-pointer",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 38.916,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 9,
        "tokens_used": 14827,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 14827},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["baked_in.go"],
        "issue_summary": "unique validator panics when slice contains nil pointer elements.",
        "root_cause": "reflect.Indirect on nil pointer returns zero reflect.Value; SetMapIndex panics. Fix: nil counter — nil elements counted separately, uniqueCount += 1 if any nils.",
        "validation_report": "4/4 subtests passed.",
        "review_notes": "",
        "patch_summary": "nilCount guard in slice/array no-param branch and map branch of isUnique in baked_in.go.",
        "current_patch": "if field.Index(i).Kind() == reflect.Ptr && field.Index(i).IsNil() { nilCount++; continue }",
        "test_stdout": "4 subtests passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 9: validator-panic-unique-nil-pointer — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:17Z",
        "task_id": "validator-panic-unique-nil-pointer",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "revise",
        "latency_seconds": 92.484,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 10,
        "tokens_used": 54106,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 10729,
            "analyst": 10226,
            "engineer": 11053,
            "tester": 10616,
            "reviewer": 11482,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["baked_in.go"],
        "issue_summary": "unique validator panics when slice contains nil pointer elements.",
        "root_cause": "reflect.Indirect on nil pointer returns zero Value. Both crash sites at lines 352 and 386 confirmed by analyst.",
        "validation_report": "4/4 subtests passed.",
        "review_notes": "REVISE: nil guard misses interface-typed nils (Kind==Interface not Ptr). param!='' branch still unguarded (latent panic). Fix incomplete for interface slices.",
        "patch_summary": "nilCount guard in slice/array no-param and map branches of isUnique.",
        "current_patch": "if field.Index(i).Kind() == reflect.Ptr && field.Index(i).IsNil() { nilCount++; continue }",
        "test_stdout": "4 subtests passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try. Reviewer flagged interface-nil blind spot and unguarded param branch.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 10: testify-mock-assert-expectations-panic — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:18Z",
        "task_id": "testify-mock-assert-expectations-panic",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 149.651,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 19,
        "tokens_used": 22881,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 22881},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["mock/mock.go"],
        "issue_summary": "AssertExpectationsForObjects panics when value-type mock.Mock is passed instead of pointer.",
        "root_cause": "Bare type assertion m := obj.(assertExpectationiser) panics for value types. Fix: ok-guard with t.Errorf + return false.",
        "validation_report": "2/2 subtests passed after test file correction (m.Called() → m.MethodCalled).",
        "review_notes": "",
        "patch_summary": "ok-guard at line 610 of mock/mock.go.",
        "current_patch": "m, ok := obj.(assertExpectationiser); if !ok { t.Errorf(...); return false }",
        "test_stdout": "2 subtests passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Fix correct on first try. Test file required correction (m.Called() → m.MethodCalled) as test authoring issue unrelated to the fix.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 10: testify-mock-assert-expectations-panic — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:19Z",
        "task_id": "testify-mock-assert-expectations-panic",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 69.770,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 12,
        "tokens_used": 52171,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 10704,
            "analyst": 9660,
            "engineer": 9791,
            "tester": 9469,
            "reviewer": 12547,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["mock/mock.go"],
        "issue_summary": "AssertExpectationsForObjects panics when value-type mock.Mock is passed.",
        "root_cause": "Bare type assertion at line 610 panics for non-pointer types. Analyst confirmed plan correct. Engineer applied clean one-line fix.",
        "validation_report": "2/2 subtests passed.",
        "review_notes": "ACCEPT: Fix correct, low regression risk, appropriately scoped.",
        "patch_summary": "ok-guard at line 610 of mock/mock.go with t.Errorf + return false.",
        "current_patch": "m, ok := obj.(assertExpectationiser); if !ok { t.Errorf(...); return false }",
        "test_stdout": "2 subtests passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 11: clap-builder-quote-empty-default — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:20Z",
        "task_id": "clap-builder-quote-empty-default",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 16.157,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 3,
        "tokens_used": 11375,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 11375},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["clap_builder/src/util/escape.rs"],
        "issue_summary": "Empty string default values render as invisible blanks in clap help output instead of \"\".",
        "root_cause": "needs_escaping() only checked for whitespace; empty string has no whitespace so fell through to Display, rendering as nothing.",
        "validation_report": "2/2 tests passed: test_real_empty_default_is_quoted, test_real_non_empty_default_without_spaces_not_quoted.",
        "review_notes": "",
        "patch_summary": "Added self.0.is_empty() || to needs_escaping() at line 8 of escape.rs.",
        "current_patch": "self.0.is_empty() || self.0.contains(char::is_whitespace)",
        "test_stdout": "2 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 11: clap-builder-quote-empty-default — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:21Z",
        "task_id": "clap-builder-quote-empty-default",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 59.933,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 9,
        "tokens_used": 54963,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 10738,
            "analyst": 10974,
            "engineer": 10703,
            "tester": 10625,
            "reviewer": 11923,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["clap_builder/src/util/escape.rs"],
        "issue_summary": "Empty string default values render as invisible blanks in clap help output.",
        "root_cause": "needs_escaping() only checked whitespace. Analyst confirmed lines 13/23 already use Debug when needs_escaping() returns true.",
        "validation_report": "2/2 tests passed.",
        "review_notes": "ACCEPT: Fix correct, low regression risk, tightly scoped. Reviewer suggested unit test for Escape(\"\").",
        "patch_summary": "self.0.is_empty() || added to needs_escaping() at line 8.",
        "current_patch": "self.0.is_empty() || self.0.contains(char::is_whitespace)",
        "test_stdout": "2 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 12: clap-parser-help-propagate-ignore-errors — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:22Z",
        "task_id": "clap-parser-help-propagate-ignore-errors",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 139.482,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 33,
        "tokens_used": 938,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 938},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["clap_builder/src/parser/parser.rs"],
        "issue_summary": "--help silenced in subcommands with ignore_errors set; real errors not silenced when subcommand sets its own ignore_errors.",
        "root_cause": "Line 747 only checked partial_parsing_enabled (parent's flag) with no use_stderr() guard, silencing --help and missing subcommand's own ignore_errors flag.",
        "validation_report": "2/2 tests passed after fix applied.",
        "review_notes": "",
        "patch_summary": "Line 747: partial_parsing_enabled → (partial_parsing_enabled || sc.is_ignore_errors_set()) && error.use_stderr().",
        "current_patch": "if (partial_parsing_enabled || sc.is_ignore_errors_set()) && error.use_stderr() {",
        "test_stdout": "2 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Agent hit rate limit mid-run but fix was already applied and is correct. Broader than fix_commit — also adds sc.is_ignore_errors_set() to cover subcommand's own flag.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 12: clap-parser-help-propagate-ignore-errors — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:23Z",
        "task_id": "clap-parser-help-propagate-ignore-errors",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 80.116,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 15,
        "tokens_used": 57888,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 10922,
            "analyst": 12283,
            "engineer": 10455,
            "tester": 10454,
            "reviewer": 13774,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["clap_builder/src/parser/parser.rs"],
        "issue_summary": "--help silenced in subcommands with ignore_errors; real errors not silenced for subcommand's own ignore_errors.",
        "root_cause": "Analyst confirmed use_stderr() exists, sc is in scope, and partial_parsing_enabled only covers parent. Fix brings subcommand path to parity with top-level command.rs logic.",
        "validation_report": "2/2 tests passed.",
        "review_notes": "ACCEPT: Fix correct, low regression risk. Reviewer noted partial_parsing_enabled variable name now misleading — suggest renaming to parent_ignore_errors (cosmetic).",
        "patch_summary": "Line 747: partial_parsing_enabled → (partial_parsing_enabled || sc.is_ignore_errors_set()) && error.use_stderr().",
        "current_patch": "if (partial_parsing_enabled || sc.is_ignore_errors_set()) && error.use_stderr() {",
        "test_stdout": "2 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 13: clap-parser-value-terminator-regression — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:24Z",
        "task_id": "clap-parser-value-terminator-regression",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 170.687,
        "iterations": 3,
        "revision_count": 2,
        "llm_calls_used": 30,
        "tokens_used": 31259,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 31259},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["clap_builder/src/parser/parser.rs"],
        "issue_summary": "value_terminator with last=true positional — values after terminator treated as unknown arguments.",
        "root_cause": "After pos_counter += 1 when terminator fires, trailing_values was not set for the next positional with last=true. Fix: check if next positional is last-flagged and set trailing_values=true.",
        "validation_report": "1/1 test passed. Also ran 909 builder tests — all pass.",
        "review_notes": "",
        "patch_summary": "After pos_counter += 1 at line 418, added next_is_last check and trailing_values=true when next positional has last=true.",
        "current_patch": "if next_is_last && !arg_os.is_escape() { trailing_values = true; matcher.start_trailing(); }",
        "test_stdout": "1 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "FAILED attempt 1: set trailing_values unconditionally when contains_last — broke escape_like_value_terminator test. FAILED attempt 2: only set when next_is_last without !is_escape guard — broke -- as terminator case. Correct on attempt 3 with !is_escape guard.",
        "first_attempt_passed": False,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 13: clap-parser-value-terminator-regression — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:25Z",
        "task_id": "clap-parser-value-terminator-regression",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "revise",
        "latency_seconds": 96.816,
        "iterations": 2,
        "revision_count": 1,
        "llm_calls_used": 17,
        "tokens_used": 61188,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 12191,
            "analyst": 11382,
            "engineer": 11315,
            "tester": 10899,
            "reviewer": 15401,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["clap_builder/src/parser/parser.rs"],
        "issue_summary": "value_terminator with last=true positional — values after terminator treated as unknown arguments.",
        "root_cause": "Coordinator initially targeted fix_commit's escape-path (line 130-144) which fixes -- as terminator, but injected test uses ; as terminator. Real fix is in positional parsing loop (~line 418).",
        "validation_report": "1/1 test passed after orchestrator applied single agent's fix.",
        "review_notes": "REVISE: Reviewer flagged !arg_os.is_escape() guard is always true in this branch (-- handled earlier), start_trailing() may be no-op after resolve_pending, and missing inline comment explaining scope.",
        "patch_summary": "After pos_counter += 1 at ~line 418: added next_is_last check and trailing_values=true/start_trailing when next positional is last-flagged.",
        "current_patch": "if next_is_last && !arg_os.is_escape() { trailing_values = true; matcher.start_trailing(); }",
        "test_stdout": "1 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "FAILED attempt 1 (engineer): applied fix_commit escape-path change which doesn't cover ; terminator. Orchestrator corrected with single agent's fix on attempt 2.",
        "first_attempt_passed": False,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 14: clap-complete-zsh-optional-value-args — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:26Z",
        "task_id": "clap-complete-zsh-optional-value-args",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 17.623,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 4,
        "tokens_used": 18684,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 18684},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["clap_complete/src/aot/shells/zsh.rs"],
        "issue_summary": "Zsh completion for optional-value arguments is broken — vc.repeat(0) produces empty spec.",
        "root_cause": "vc.repeat(0) returns empty string when min_values==0, stripping the value spec entirely so Zsh treats the option as a boolean flag.",
        "validation_report": "1/1 test passed: test_real_optional_value_arg_has_zsh_value_spec.",
        "review_notes": "",
        "patch_summary": "Line 482: branch on min_values()==0 — prepend ':' to vc (producing '::name:completion' = Zsh optional-value syntax) instead of repeat(0).",
        "current_patch": "if min == 0 { format!(\":{vc}\") } else { vc.repeat(min) }",
        "test_stdout": "1 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 14: clap-complete-zsh-optional-value-args — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:27Z",
        "task_id": "clap-complete-zsh-optional-value-args",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "revise",
        "latency_seconds": 57.236,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 6,
        "tokens_used": 60645,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 17387,
            "analyst": 10987,
            "engineer": 10518,
            "tester": 10330,
            "reviewer": 11423,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["clap_complete/src/aot/shells/zsh.rs"],
        "issue_summary": "Zsh completion for optional-value arguments is broken.",
        "root_cause": "vc.repeat(0) returns empty string. Analyst confirmed vc starts with ':' so prepending ':' yields '::name:completion' which is correct Zsh optional-value syntax.",
        "validation_report": "1/1 test passed.",
        "review_notes": "REVISE: Reviewer incorrectly flagged '::name:completion' as malformed — this is actually correct Zsh syntax for optional values. Test passes; fix is sound.",
        "patch_summary": "Line 482: if min_values()==0 prepend ':' to vc, else vc.repeat(min).",
        "current_patch": "if min == 0 { format!(\":{vc}\") } else { vc.repeat(min) }",
        "test_stdout": "1 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Correct on first try.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 15: clap-builder-default-vals-newline — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:28Z",
        "task_id": "clap-builder-default-vals-newline",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 115.949,
        "iterations": 2,
        "revision_count": 1,
        "llm_calls_used": 18,
        "tokens_used": 20042,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 20042},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["clap_builder/src/output/help_template.rs"],
        "issue_summary": "Default value appears on same line as possible values in help when arg has no prose help text.",
        "root_cause": "Two issues: (1) use_long_pv required per-value help text, so plain values never triggered the Possible values block; (2) separator before spec_vals only emitted when help_is_empty=false.",
        "validation_report": "1/1 test passed. 345 clap_builder tests pass.",
        "review_notes": "",
        "patch_summary": "Changed use_long_pv to !is_empty(); added has_possible_values tracking; changed separator condition to !help_is_empty || has_possible_values.",
        "current_patch": "use_long_pv: self.use_long && !arg.get_possible_values().is_empty(); separator: if !help_is_empty || has_possible_values",
        "test_stdout": "1 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "FAILED attempt 1: fixed separator only — test still failed because use_long_pv blocked the Possible values block for plain values. Correct on attempt 2 after also fixing use_long_pv.",
        "first_attempt_passed": False,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 15: clap-builder-default-vals-newline — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:29Z",
        "task_id": "clap-builder-default-vals-newline",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "revise",
        "latency_seconds": 144.090,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 28,
        "tokens_used": 81075,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 23724,
            "analyst": 13330,
            "engineer": 14761,
            "tester": 10371,
            "reviewer": 18889,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["clap_builder/src/output/help_template.rs"],
        "issue_summary": "Default value appears on same line as possible values in help when arg has no prose help text.",
        "root_cause": "Analyst correctly identified that coordinator's plan alone was insufficient — use_long_pv also needed fixing. Both fixes applied by engineer.",
        "validation_report": "1/1 test passed.",
        "review_notes": "REVISE: Reviewer flagged use_long_pv change as too broad — forces verbose block for all possible-value args even without per-value help text, regressing compact inline format. Suggests reverting use_long_pv and keeping only the separator fix (which would only matter when values have help text).",
        "patch_summary": "Changed use_long_pv to !is_empty(); added has_possible_values; separator condition to !help_is_empty || has_possible_values.",
        "current_patch": "use_long_pv: self.use_long && !arg.get_possible_values().is_empty(); separator: if !help_is_empty || has_possible_values",
        "test_stdout": "1 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Analyst caught coordinator plan was incomplete. Engineer applied both fixes correctly. Test passes.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 16: react-router-create-routes-stub — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:00Z",
        "task_id": "react-router-create-routes-stub",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 49.806,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 11,
        "tokens_used": 14935,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 14935},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["packages/react-router/lib/components.tsx"],
        "issue_summary": "Framework Mode route components typed with Route.ComponentProps are unassignable to React.ComponentType<RouteComponentProps> in StubRouteExtensions due to TypeScript contravariance on params/matches types.",
        "root_cause": "RouteComponentType, HydrateFallbackType, and ErrorBoundaryType in components.tsx used specific props types, making Framework Mode components with narrower param types unassignable. Fix widens all three to React.ComponentType<any>.",
        "validation_report": "2/2 tests passed.",
        "review_notes": "accept",
        "patch_summary": "Changed RouteComponentType, HydrateFallbackType, ErrorBoundaryType from ComponentType<SpecificProps> to ComponentType<any> at lines 1939, 1966, 1994.",
        "current_patch": "RouteComponentType = React.ComponentType<any>; HydrateFallbackType = React.ComponentType<any>; ErrorBoundaryType = React.ComponentType<any>",
        "test_stdout": "2 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Agent identified correct lines (1939, 1966, 1994) and applied all three type widenings on the first try.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 16: react-router-create-routes-stub — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:00Z",
        "task_id": "react-router-create-routes-stub",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "revise",
        "latency_seconds": 94.069,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 19,
        "tokens_used": 63323,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 11122,
            "analyst": 11765,
            "engineer": 11967,
            "tester": 10524,
            "reviewer": 17945,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["packages/react-router/lib/components.tsx"],
        "issue_summary": "Framework Mode route components typed with Route.ComponentProps are unassignable to React.ComponentType<RouteComponentProps> in StubRouteExtensions due to TypeScript contravariance on params/matches types.",
        "root_cause": "Coordinator correctly identified lines 1939, 1966, 1994. Analyst confirmed and flagged that ComponentType<any> is overly broad but correct. Engineer applied all three changes. Tester confirmed 2/2 pass. Reviewer recommended REVISE: suggests Partial<RouteComponentProps> as a more type-safe alternative.",
        "validation_report": "2/2 tests passed.",
        "review_notes": "REVISE: Reviewer flagged that React.ComponentType<any> sacrifices type safety; suggests Partial<RouteComponentProps> to preserve as much type safety as possible while resolving assignability.",
        "patch_summary": "Changed RouteComponentType, HydrateFallbackType, ErrorBoundaryType from ComponentType<SpecificProps> to ComponentType<any> at lines 1939, 1966, 1994.",
        "current_patch": "RouteComponentType = React.ComponentType<any>; HydrateFallbackType = React.ComponentType<any>; ErrorBoundaryType = React.ComponentType<any>",
        "test_stdout": "2 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Coordinator plan was accurate. Analyst confirmed correctness with caveat about type safety loss. Engineer applied fix cleanly. Tests passed.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 17: react-router-double-slash-colon-path — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:00Z",
        "task_id": "react-router-double-slash-colon-path",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 23.523,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 5,
        "tokens_used": 13176,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 13176},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["packages/react-router/lib/router/utils.ts"],
        "issue_summary": "resolvePath incorrectly treats colon-containing relative paths like 'foo:bar' as absolute URLs due to isAbsoluteUrl check, bypassing proper relative path resolution.",
        "root_cause": "Removed the isAbsoluteUrl(toPathname) guard in resolvePath so double-slash normalization and absolute/relative resolution runs unconditionally. foo:bar now resolves as a relative path.",
        "validation_report": "6/6 tests passed.",
        "review_notes": "accept",
        "patch_summary": "Removed isAbsoluteUrl branch (~lines 1606-1608 and closing brace 1623) in resolvePath in utils.ts.",
        "current_patch": "Removed if (isAbsoluteUrl(toPathname)) { pathname = toPathname; } else { ... } wrapper",
        "test_stdout": "6 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Agent correctly identified isAbsoluteUrl check as the culprit and removed it.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 17: react-router-double-slash-colon-path — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:00Z",
        "task_id": "react-router-double-slash-colon-path",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "revise",
        "latency_seconds": 124.38,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 24,
        "tokens_used": 66852,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 11872,
            "analyst": 12344,
            "engineer": 11380,
            "tester": 10899,
            "reviewer": 20357,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["packages/react-router/lib/router/utils.ts"],
        "issue_summary": "resolvePath incorrectly treats colon-containing relative paths like 'foo:bar' as absolute URLs due to isAbsoluteUrl check.",
        "root_cause": "Coordinator identified lines 1606-1623. Analyst confirmed but noted the branch may also silently handle protocol-relative URLs. Engineer removed the branch. Tests passed. Reviewer flagged REVISE: removing the guard entirely breaks protocol-relative URLs (//google.com becomes /google.com), pre-existing test resolvePath-test.tsx fails.",
        "validation_report": "6/6 tests passed.",
        "review_notes": "REVISE: Reviewer found that removing isAbsoluteUrl entirely corrupts protocol-relative URLs (//google.com → /google.com). Suggests narrowing guard to only match true external URLs (containing ://) rather than removing it completely.",
        "patch_summary": "Removed isAbsoluteUrl branch in resolvePath.",
        "current_patch": "Removed if (isAbsoluteUrl(toPathname)) guard and else wrapper",
        "test_stdout": "6 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Fix worked for target test but reviewer found regression with protocol-relative URLs.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 18: react-router-optional-segment-slash — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:00Z",
        "task_id": "react-router-optional-segment-slash",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "accept",
        "latency_seconds": 34.490,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 7,
        "tokens_used": 13888,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 13888},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["packages/react-router/lib/router/utils.ts"],
        "issue_summary": "compilePath converts :param? to regex /?([^\\/]+)? making the slash optional, so /test/:part? incorrectly matches /test_more.",
        "root_cause": "Updated compilePath callback to inspect nextChar after the match. If non-slash nextChar: return /([^\\/]*) (slash required). Otherwise: return (?:/([^\\/]*))?",
        "validation_report": "10/10 tests passed.",
        "review_notes": "accept",
        "patch_summary": "Added offset/str params to replace callback in compilePath, compute nextChar, bifurcate optional segment regex based on following character.",
        "current_patch": "isOptional && nextChar && nextChar !== '/' ? '/([^\\/]*)' : '(?:/([^\\/]*))?'",
        "test_stdout": "10 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Agent correctly identified the regex pattern and applied the nextChar bifurcation.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 18: react-router-optional-segment-slash — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:00Z",
        "task_id": "react-router-optional-segment-slash",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "revise",
        "latency_seconds": 190.12,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 22,
        "tokens_used": 65116,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 10992,
            "analyst": 12357,
            "engineer": 11345,
            "tester": 10462,
            "reviewer": 19960,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["packages/react-router/lib/router/utils.ts"],
        "issue_summary": "compilePath converts :param? to /?([^\\/]+)? making slash optional, allowing /test/:part? to match /test_more.",
        "root_cause": "Coordinator/analyst correctly identified lines 1494-1498. Engineer applied nextChar bifurcation. Tests passed. Reviewer flagged REVISE: non-slash nextChar branch is unreachable in valid patterns and semantically wrong; simplification to (?:/([^\\/]*))? may be cleaner.",
        "validation_report": "10/10 tests passed.",
        "review_notes": "REVISE: Reviewer flagged that the non-slash nextChar branch is unreachable in valid React Router patterns and uses [^\\/]* (zero-or-more) where + (one-or-more) would be more correct. Suggests simpler (?:/([^\\/]+))? approach.",
        "patch_summary": "Added offset/str params to compilePath replace callback, nextChar check bifurcates optional segment regex.",
        "current_patch": "isOptional && nextChar && nextChar !== '/' ? '/([^\\/]*)' : '(?:/([^\\/]*))?'",
        "test_stdout": "10 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. All 5 agents agreed on approach. Reviewer noted edge cases.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 19: react-router-percent-encoding — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:00Z",
        "task_id": "react-router-percent-encoding",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "revise",
        "latency_seconds": 522.172,
        "iterations": 5,
        "revision_count": 4,
        "llm_calls_used": 69,
        "tokens_used": 73024,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 73024},
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["packages/react-router/lib/hooks.tsx"],
        "issue_summary": "useHref double-encodes percent-encoded characters (%20 → %2520) when navigating to relative paths with special characters.",
        "root_cause": "Bug not present at this base commit in runtime code path; none of resolveTo/joinPaths/createHref perform encoding. Agent added defensive normalization: joinedPathname.replace(/%25([0-9A-Fa-f]{2})/g, '%$1') before navigator.createHref.",
        "validation_report": "12/12 tests passed.",
        "review_notes": "revise",
        "patch_summary": "Added %25XX → %XX normalization on joinedPathname in useHref before navigator.createHref call.",
        "current_patch": "joinedPathname = joinedPathname.replace(/%25([0-9A-Fa-f]{2})/g, '%$1');",
        "test_stdout": "12 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "FAILED attempts 1-4: attempt 1 used encodeURIComponent(decodeURIComponent()) which over-encoded sub-delimiters; attempt 2 used decodeURI which decoded %20 to space; attempts 3-4 tried different decode strategies that broke other tests. Correct on attempt 5 with %25XX regex normalization.",
        "first_attempt_passed": False,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 19: react-router-percent-encoding — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:00Z",
        "task_id": "react-router-percent-encoding",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "success",
        "validation_passed": True,
        "review_recommendation": "revise",
        "latency_seconds": 218.882,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 64,
        "tokens_used": 128386,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 34976,
            "analyst": 19789,
            "engineer": 11069,
            "tester": 10540,
            "reviewer": 52012,
        },
        "test_returncode": 0,
        "regression_passed": None,
        "changed_files": ["packages/react-router/lib/hooks.tsx"],
        "issue_summary": "useHref double-encodes percent-encoded characters (%20 → %2520) when navigating to relative paths with special characters.",
        "root_cause": "Analyst confirmed no double-encoding exists in runtime code at this commit. Coordinator/engineer applied %25XX normalization defensively. Reviewer flagged REVISE: fix is lossy (corrupts legitimate %25XX sequences), not applied symmetrically to useNavigate, and should be at the encoding boundary (encodeLocation/createURL) not useHref.",
        "validation_report": "12/12 tests passed.",
        "review_notes": "REVISE: Reviewer flagged that %25XX regex is lossy (corrupts legitimate percent-encoded percent signs), not symmetric with useNavigate, and applied at wrong layer — fix should be in encodeLocation where encoding actually occurs.",
        "patch_summary": "Added %25XX → %XX normalization on joinedPathname in useHref before navigator.createHref.",
        "current_patch": "joinedPathname = joinedPathname.replace(/%25([0-9A-Fa-f]{2})/g, '%$1');",
        "test_stdout": "12 passed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "1 attempt. Analyst noted bug not present at this commit. Engineer applied fix as directed. Tests passed.",
        "first_attempt_passed": True,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 20: react-router-client-loader-hydrate — SINGLE AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:00Z",
        "task_id": "react-router-client-loader-hydrate",
        "architecture": "single",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "failure",
        "validation_passed": False,
        "review_recommendation": "revise",
        "latency_seconds": 0,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 0,
        "tokens_used": 0,
        "cached_tokens": 0,
        "tokens_by_role": {"single": 0},
        "test_returncode": 1,
        "regression_passed": None,
        "changed_files": [],
        "issue_summary": "Child route with clientLoader+HydrateFallback does not render HydrateFallback when ancestor route loader is still pending during hydration.",
        "root_cause": "Hard task — hydration loop in router.ts evaluates each route independently with getRouteHydrationStatus, not propagating ancestor-hydrating state to children. Fix attempts (adding ancestorIsHydrating flag) did not resolve the test failure.",
        "validation_report": "1 failed, 12 passed.",
        "review_notes": "failed",
        "patch_summary": "",
        "current_patch": "",
        "test_stdout": "1 failed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "Task timed out / agent could not produce a passing fix. Hard difficulty — deep router hydration logic.",
        "first_attempt_passed": False,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

    # -------------------------------------------------------------------------
    # Task 20: react-router-client-loader-hydrate — MULTI AGENT
    # -------------------------------------------------------------------------
    {
        "suite_id": "suite-manual-2026-04-16",
        "timestamp_utc": "2026-04-16T00:00:00Z",
        "task_id": "react-router-client-loader-hydrate",
        "architecture": "multi",
        "repeat_index": 0,
        "mode": "claude-subagent",
        "model": "claude-sonnet-4-6",
        "final_status": "failure",
        "validation_passed": False,
        "review_recommendation": "revise",
        "latency_seconds": 147.407,
        "iterations": 1,
        "revision_count": 0,
        "llm_calls_used": 24,
        "tokens_used": 58547,
        "cached_tokens": 0,
        "tokens_by_role": {
            "coordinator": 16475,
            "analyst": 14193,
            "engineer": 15354,
            "tester": 12525,
            "reviewer": 0,
        },
        "test_returncode": 1,
        "regression_passed": None,
        "changed_files": ["packages/react-router/lib/router/router.ts"],
        "issue_summary": "Child route with clientLoader+HydrateFallback does not render HydrateFallback when ancestor route loader is still pending during hydration.",
        "root_cause": "Coordinator/analyst correctly identified lines 1028-1032 and 5004-5011. Engineer applied ancestorIsHydrating propagation but test still failed — child-fallback remained null. Reviewer not reached due to test failure.",
        "validation_report": "1 failed, 12 passed.",
        "review_notes": "failed",
        "patch_summary": "Added ancestorIsHydrating tracking in hydration loop and getMatchesToLoad initialHydration branch.",
        "current_patch": "ancestorIsHydrating propagation in relevantMatches.every loop and matches.map initialHydration branch",
        "test_stdout": "1 failed",
        "test_stderr": "",
        "selected_branch_id": "",
        "branch_results": [],
        "attempt_notes": "Engineer fix applied but test still failed. Hard difficulty task — deep router hydration state machine logic.",
        "first_attempt_passed": False,
        "logs": [],
        "transcript": [],
        "messages": [],
    },

]


# ---------------------------------------------------------------------------
# Inject logic — no need to edit below this line
# ---------------------------------------------------------------------------

def _build_record(entry: dict) -> BenchmarkRunRecord:
    task = get_task(entry["task_id"])
    suite_id = entry["suite_id"]
    architecture = entry["architecture"]
    repeat_index = entry["repeat_index"]
    run_id = f"{suite_id}-{entry['task_id']}-{architecture}-r{repeat_index + 1}"

    tokens_used = entry.get("tokens_used", 0)
    token_budget_exceeded = tokens_used > 60000

    return BenchmarkRunRecord(
        run_id=run_id,
        suite_id=suite_id,
        timestamp_utc=entry["timestamp_utc"],
        task_id=entry["task_id"],
        task_title=task["title"],
        task_type=task.get("task_type", "real"),
        fix_date=task.get("fix_date", ""),
        repository=task["repository"],
        architecture=architecture,
        workflow_label="single-agent baseline" if architecture == "single" else "multi-agent workflow",
        role_count=1 if architecture == "single" else 5,
        engineer_worker_count=1,
        repeat_index=repeat_index,
        mode=entry.get("mode", "claude-subagent"),
        model=entry.get("model", "claude-sonnet-4-6"),
        prompt_version="faang-v1",
        max_iterations=15,
        max_revision_rounds=5,
        max_llm_calls=80 if architecture == "single" else 120,
        final_status=entry["final_status"],
        validation_passed=entry["validation_passed"],
        review_recommendation=entry.get("review_recommendation", ""),
        latency_seconds=entry["latency_seconds"],
        iterations=entry.get("iterations", 1),
        revision_count=entry.get("revision_count", 0),
        llm_calls_used=entry["llm_calls_used"],
        tokens_used=tokens_used,
        cached_tokens=entry.get("cached_tokens", 0),
        tokens_by_role=entry.get("tokens_by_role", {}),
        token_budget_exceeded=token_budget_exceeded,
        test_returncode=entry.get("test_returncode"),
        regression_passed=entry.get("regression_passed"),
        failure_category="success" if entry["final_status"] == "success" else "test_failed",
        changed_files=entry.get("changed_files", []),
        validation_report=entry.get("validation_report", ""),
        review_notes=entry.get("review_notes", ""),
        issue_summary=entry.get("issue_summary", ""),
        root_cause=entry.get("root_cause", ""),
        logs=entry.get("logs", []),
        transcript=entry.get("transcript", []),
        messages=entry.get("messages", []),
        patch_summary=entry.get("patch_summary", ""),
        current_patch=entry.get("current_patch", ""),
        test_stdout=entry.get("test_stdout", ""),
        test_stderr=entry.get("test_stderr", ""),
        selected_branch_id=entry.get("selected_branch_id", ""),
        branch_results=entry.get("branch_results", []),
        attempt_notes=entry.get("attempt_notes", ""),
        first_attempt_passed=bool(entry.get("first_attempt_passed", True)),
    )


def main() -> None:
    benchmark_root = Path("benchmark_runs").resolve()
    records = [_build_record(e) for e in MANUAL_RUNS]

    for record in records:
        label = _TASK_FOLDER_LABEL.get(record.task_id, record.task_id)
        arch_dir = benchmark_root / label / record.architecture
        raw_dir = arch_dir / "raw"
        arch_dir.mkdir(parents=True, exist_ok=True)
        raw_dir.mkdir(exist_ok=True)

        raw_path = raw_dir / f"{record.run_id}.json"
        raw_path.write_text(json.dumps(asdict(record), indent=2))
        print(f"wrote {raw_path}")

    # Write per-task-per-arch summary.json
    from collections import defaultdict
    arch_records: dict[tuple, list] = defaultdict(list)
    for rec in records:
        arch_records[(rec.task_id, rec.architecture)].append(rec)
    for (task_id, architecture), recs in arch_records.items():
        label = _TASK_FOLDER_LABEL.get(task_id, task_id)
        arch_dir = benchmark_root / label / architecture
        summary_path = arch_dir / "summary.json"
        summary_path.write_text(json.dumps(_aggregate(recs), indent=2))
        print(f"wrote {summary_path}")



if __name__ == "__main__":
    main()
